### ISSUE TITLE
你好，请问HResNet是什么网络呢，我在网上没能找到有关这个的资料

### ISSUE THREAD

**Issue by w-1nz** [lrybbs/Hyperspectral-classification-deeplearning#2]

**Comment by lrybbs** [comment]
是一篇letter里面提到的，名字叫《Multitask Deep Learning With Spectral Knowledge for Hyperspectral Image Classification》

**Comment by lrybbs** [comment]
是一篇letter里面提到的，名字叫《Multitask Deep Learning With Spectral Knowledge for Hyperspectral Image Classification》



在 2023-05-13 13:23:40，"wwwhzzz" ***@***.***> 写道：
