### ISSUE TITLE
Hello, may I ask you a question? May I ask if this code meets the accuracy of the paper's reproduction? I would like to quote your project.

### ISSUE THREAD

**Issue by chihuajiao** [lrybbs/Hyperspectral-classification-deeplearning#3]

**Comment by lrybbs** [comment]
which paper?

**Comment by chihuajiao** [comment]
Hello, I saw the answer from the previous issue, and I'm sorry for any misunderstanding caused. It's this paper Multitask Deep Learning With Spectral Knowledge for Hyperspectral Image Classification.

**Comment by lrybbs** [comment]
I have tried to use HResnet for multi task work. Maybe my hyperparameter adjustment is bad, only when the number of samples of each class <= 30 can approach the performance of multi task learning in the paper. When the number of samples of each classes reaches 50, the performance of single task exceeds multi tasks.

**Comment by chihuajiao** [comment]
Thank you very much for your help and I wish you success in your studies.
